<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|    http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$config['base_url'] = 'https://www.swanntechnologies.com/OscarsBallotPredictions/';
//$config['base_url'] = 'http://localhost:8080/oscaraward/';
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = sys_get_temp_dir();
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/


$config['problems'] = array(
array('title'=>'ACTOR IN A LEADING ROLE', 'score'=>7, 'data'=>array(
				'JAVIER BARDEM, “Being the Ricardos”',
				'BENEDICT CUMBERBATCH, “The Power of the Dog”',
				'ANDREW GARFIELD, “tick, tick...BOOM!”',
				'WILL SMITH, “King Richard”',
				'DENZEL WASHINGTON, “The Tragedy of Macbeth”'
			)),
array('title'=>'ACTOR IN A SUPPORTING ROLE', 'score'=>7, 'data'=>array(
				'CIARÁN HINDS, “Belfast”',
				'TROY KOTSUR, “CODA”',
				'JESSE PLEMONS, “The Power of the Dog”',
				'J.K. SIMMONS, “Being the Ricardos”',
				'KODI SMIT-MCPHEE, “The Power of the Dog”'
			)),
array('title'=>'ACTRESS IN A LEADING ROLE', 'score'=>7, 'data'=>array(
				'JESSICA CHASTAIN, “The Eyes of Tammy Faye”',
				'OLIVIA COLMAN, “The Lost Daughter”',
				'PENÉLOPE CRUZ, “Parallel Mothers”',
				'NICOLE KIDMAN, “Being the Ricardos”',
				'KRISTEN STEWART, “Spencer”'
			)),
array('title'=>'ACTRESS IN A SUPPORTING ROLE', 'score'=>7, 'data'=>array(
				'JESSIE BUCKLEY, “The Lost Daughter”',
				'ARIANA DEBOSE, “West Side Story”',
				'JUDI DENCH, “Belfast”',
				'KIRSTEN DUNST, “The Power of the Dog”',
				'AUNJANUE ELLIS, “King Richard”'
			)),
array('title'=>'ANIMATED FEATURE FILM', 'score'=>5, 'data'=>array(
				'”ENCANTO”, Jared Bush, Byron Howard, Yvett Merino and Clark Spencer',
				'”FLEE”, Jonas Poher Rasmussen, Monica Hellström, Signe Byrge Sørensen and Charlotte De La Gournerie',
				'”LUCA”, Enrico Casarosa and Andrea Warren',
				'”THE MITCHELLS VS. THE MACHINES”, Mike Rianda, Phil Lord, Christopher Miller and Kurt Albrecht',
				'”RAYA AND THE LAST DRAGON”, Don Hall, Carlos López Estrada, Osnat Shurer and Peter Del Vecho'
			)),
array('title'=>'CINEMATOGRAPHY', 'score'=>3, 'data'=>array(
				'”DUNE”, Greig Fraser',
				'”NIGHTMARE ALLEY”, Dan Laustsen',
				'”THE POWER OF THE DOG”, Ari Wegner',
				'”THE TRAGEDY OF MACBETH”, Bruno Delbonnel',
				'”WEST SIDE STORY”, Janusz Kaminski'
			)),
array('title'=>'COSTUME DESIGN', 'score'=>3, 'data'=>array(
				'”CRUELLA”, Jenny Beavan',
				'”CYRANO”, Massimo Cantini Parrini and Jacqueline Durran',
				'”DUNE”, Jacqueline West and Robert Morgan',
				'”NIGHTMARE ALLEY”, Luis Sequeira',
				'”WEST SIDE STORY”, Paul Tazewell'
			)),
array('title'=>'DIRECTING', 'score'=>7, 'data'=>array(
				'”BELFAST”, Kenneth Branagh',
				'”DRIVE MY CAR”, Ryusuke Hamaguchi',
				'”LICORICE PIZZA”, Paul Thomas Anderson',
				'”THE POWER OF THE DOG”, Jane Campion',
				'”WEST SIDE STORY”, Steven Spielberg'
			)),
array('title'=>'DOCUMENTARY (FEATURE)', 'score'=>2, 'data'=>array(
				'”ASCENSION”, Jessica Kingdon, Kira Simon-Kennedy and Nathan Truesdell',
				'”ATTICA”, Stanley Nelson and Traci A. Curry',
				'”FLEE”, Jonas Poher Rasmussen, Monica Hellström, Signe Byrge Sørensen and Charlotte De La Gournerie',
				'”SUMMER OF SOUL (...OR, WHEN THE REVOLUTION COULD NOT BE TELEVISED)”, Ahmir "Questlove" Thompson, Joseph Patel, Robert Fyvolent and David Dinerstein',
				'”WRITING WITH FIRE”, Rintu Thomas and Sushmit Ghosh'
			)),
array('title'=>'DOCUMENTARY (SHORT SUBJECT)', 'score'=>2, 'data'=>array(
				'”AUDIBLE”, Matt Ogens and Geoff McLean',
				'”LEAD ME HOME”, Pedro Kos and Jon Shenk',
				'”THE QUEEN OF BASKETBALL”, Ben Proudfoot',
				'”THREE SONGS FOR BENAZIR”, Elizabeth Mirzaei and Gulistan Mirzaei',
				'”WHEN WE WERE BULLIES”, Jay Rosenblatt'
			)),
array('title'=>'FILM EDITING', 'score'=>3, 'data'=>array(
				'”DON\'T LOOK UP”, Hank Corwin',
				'”DUNE”, Joe Walker',
				'”KING RICHARD”, Pamela Martin',
				'”THE POWER OF THE DOG”, Peter Sciberras',
				'”TICK, TICK...BOOM!”, Myron Kerstein and Andrew Weisblum'
			)),
array('title'=>'INTERNATIONAL FEATURE FILM', 'score'=>5, 'data'=>array(
				'”DRIVE MY CAR”, Japan',
				'”FLEE”, Denmark',
				'”THE HAND OF GOD”, Italy',
				'”LUNANA: A YAK IN THE CLASSROOM”, Bhutan',
				'”THE WORST PERSON IN THE WORLD”, Norway'
			)),
array('title'=>'MAKEUP AND HAIRSTYLING', 'score'=>3, 'data'=>array(
				'”COMING 2 AMERICA”, Mike Marino, Stacey Morris and Carla Farmer',
				'”CRUELLA”, Nadia Stacey, Naomi Donne and Julia Vernon',
				'”DUNE”, Donald Mowat, Love Larson and Eva von Bahr',
				'”THE EYES OF TAMMY FAYE”, Linda Dowds, Stephanie Ingram and Justin Raleigh',
				'”HOUSE OF GUCCI”, Göran Lundström, Anna Carin Lock and Frederic Aspiras'
			)),
array('title'=>'MUSIC (ORIGINAL SCORE)', 'score'=>3, 'data'=>array(
				'”DON\'T LOOK UP”, Nicholas Britell',
				'”DUNE”, Hans Zimmer',
				'”ENCANTO”, Germaine Franco',
				'”PARALLEL MOTHERS”, Alberto Iglesias',
				'”THE POWER OF THE DOG”, Jonny Greenwood'
			)),
array('title'=>'MUSIC (ORIGINAL SONG)', 'score'=>3, 'data'=>array(
				'”BE ALIVE”, from King Richard; Music and Lyric by DIXSON and Beyoncé Knowles-Carter',
				'”DOS ORUGUITAS”, from Encanto; Music and Lyric by Lin-Manuel Miranda',
				'”DOWN TO JOY”, from Belfast; Music and Lyric by Van Morrison',
				'”NO TIME TO DIE”, from No Time to Die; Music and Lyric by Billie Eilish and Finneas O\'Connell',
				'”SOMEHOW YOU DO”, from Four Good Days; Music and Lyric by Diane Warren'
			)),
array('title'=>'BEST PICTURE', 'score'=>10, 'data'=>array(
				'”BELFAST”, Laura Berwick, Kenneth Branagh, Becca Kovacik and Tamar Thomas, Producers',
				'”CODA”, Philippe Rousselet, Fabrice Gianfermi and Patrick Wachsberger, Producers',
				'”DON\'T LOOK UP”, Adam McKay and Kevin Messick, Producers',
				'”DRIVE MY CAR”, Teruhisa Yamamoto, Producer',
				'”DUNE”, Mary Parent, Denis Villeneuve and Cale Boyter, Producers',
				'”KING RICHARD”, Tim White, Trevor White and Will Smith, Producers',
				'”LICORICE PIZZA”, Sara Murphy, Adam Somner and Paul Thomas Anderson, Producers',
				'”NIGHTMARE ALLEY”, Guillermo del Toro, J. Miles Dale and Bradley Cooper, Producers',
				'”THE POWER OF THE DOG”, Jane Campion, Tanya Seghatchian, Emile Sherman, Iain Canning and Roger Frappier, Producers',
				'”WEST SIDE STORY”, Steven Spielberg and Kristie Macosko Krieger, Producers'
			)),
array('title'=>'PRODUCTION DESIGN', 'score'=>3, 'data'=>array(
				'”DUNE”, Production Design: Patrice Vermette; Set Decoration: Zsuzsanna Sipos',
				'”NIGHTMARE ALLEY”, Production Design: Tamara Deverell; Set Decoration: Shane Vieau',
				'”THE POWER OF THE DOG”, Production Design: Grant Major; Set Decoration: Amber Richards',
				'”THE TRAGEDY OF MACBETH”, Production Design: Stefan Dechant; Set Decoration: Nancy Haigh',
				'”WEST SIDE STORY”, Production Design: Adam Stockhausen; Set Decoration: Rena DeAngelo'
			)),
array('title'=>'SHORT FILM (ANIMATED)', 'score'=>2, 'data'=>array(
				'”AFFAIRS OF THE ART”, Joanna Quinn and Les Mills',
				'”BESTIA”, Hugo Covarrubias and Tevo Díaz',
				'”BOXBALLET”, Anton Dyakov',
				'”ROBIN ROBIN”, Dan Ojari and Mikey Please',
				'”THE WINDSHIELD WIPER”, Alberto Mielgo and Leo Sanchez'
			)),
array('title'=>'SHORT FILM (LIVE ACTION)', 'score'=>2, 'data'=>array(
				'”ALA KACHUU - TAKE AND RUN”, Maria Brendle and Nadine Lüchinger',
				'”THE DRESS”, Tadeusz Łysiak and Maciej Ślesicki',
				'”THE LONG GOODBYE”, Aneil Karia and Riz Ahmed',
				'”ON MY MIND”, Martin Strange-Hansen and Kim Magnusson',
				'”PLEASE HOLD”, K.D. Dávila and Levin Menekse'
			)),
array('title'=>'SOUND', 'score'=>3, 'data'=>array(
				'”BELFAST”, Denise Yarde, Simon Chase, James Mather and Niv Adiri',
				'”DUNE”, Mac Ruth, Mark Mangini, Theo Green, Doug Hemphill and Ron Bartlett',
				'”NO TIME TO DIE”, Simon Hayes, Oliver Tarney, James Harrison, Paul Massey and Mark Taylor',
				'”THE POWER OF THE DOG”, Richard Flynn, Robert Mackenzie and Tara Webb',
				'”WEST SIDE STORY”, Tod A. Maitland, Gary Rydstrom, Brian Chumney, Andy Nelson and Shawn Murphy'
			)),
array('title'=>'VISUAL EFFECTS', 'score'=>3, 'data'=>array(
				'”DUNE”, Paul Lambert, Tristan Myles, Brian Connor and Gerd Nefzer',
				'”FREE GUY”, Swen Gillberg, Bryan Grill, Nikos Kalaitzidis and Dan Sudick',
				'”NO TIME TO DIE”, Charlie Noble, Joel Green, Jonathan Fawkner and Chris Corbould',
				'”SHANG-CHI AND THE LEGEND OF THE TEN RINGS”, Christopher Townsend, Joe Farrell, Sean Noel Walker and Dan Oliver',
				'”SPIDER-MAN: NO WAY HOME”, Kelly Port, Chris Waegner, Scott Edelstein and Dan Sudick'
			)),
array('title'=>'WRITING (ADAPTED SCREENPLAY)', 'score'=>5, 'data'=>array(
				'”CODA”, Screenplay by Siân Heder',
				'”DRIVE MY CAR”, Screenplay by Ryusuke Hamaguchi, Takamasa Oe',
				'”DUNE”, Screenplay by Jon Spaihts and Denis Villeneuve and Eric Roth',
				'”THE LOST DAUGHTER”, Written by Maggie Gyllenhaal',
				'”THE POWER OF THE DOG”, Written by Jane Campion'
			)),
array('title'=>'WRITING (ORIGINAL SCREENPLAY)', 'score'=>5, 'data'=>array(
				'”BELFAST”, Written by Kenneth Branagh',
				'”DON\'T LOOK UP”, Screenplay by Adam McKay; Story by Adam McKay & David Sirota',
				'”KING RICHARD”, Written by Zach Baylin',
				'”LICORICE PIZZA”, Written by Paul Thomas Anderson',
				'”THE WORST PERSON IN THE WORLD”, Written by Eskil Vogt, Joachim Trier'
			))
	);

